// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "256 GB",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 16 Pro",
                            Price = 55000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Description = "512 GB",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Iphone 15 Pro",
                            Price = 45000m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 3,
                            Description = "256 GB",
                            ImageUrl = "3.jpg",
                            IsActive = false,
                            Name = "Macbook Air",
                            Price = 39000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Description = "512 GB",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Iphone 16 Pro Max",
                            Price = 85000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Description = "256 GB",
                            ImageUrl = "5.jpg",
                            IsActive = true,
                            Name = "Samsung S24 Plus",
                            Price = 53000m,
                            Stock = 90
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
